export const ROUTES = {
  home: "/",
  about: "/about",
  experiences: "/experiences",
  tours: "/tours",
  toursWithCountry: (countryId) =>
    countryId && countryId !== "all" ? `/tours?country=${countryId}` : "/tours",
  tourBook: (slug) => `/tours/${slug}/book`,
  tourDetail: (slug) => `/tours/${slug}`,
  whyUs: "/why-us",
  stories: "/stories",
  storyDetail: (slug) => `/stories/${slug}`,
  contact: "/contact",
  login: "/login",
  signup: "/signup",
  dashboard: "/dashboard",
  profile: "/profile",
  myInquiries: "/my-inquiries",
  myBookings: "/my-bookings",
  unauthorized: "/unauthorized",
  operator: {
    dashboard: "/operator/dashboard",
    tours: "/operator/tours",
    tourNew: "/operator/tours/new",
    tourEdit: (id) => `/operator/tours/${id}/edit`,
    bookings: "/operator/bookings",
    profile: "/operator/profile",
  },
};
