export const ROUTES = {
  home: "/",
  about: "/about",
  experiences: "/experiences",
  tours: "/tours",
  toursWithCountry: (countryId) =>
    countryId && countryId !== "all" ? `/tours?country=${countryId}` : "/tours",
  tourBook: (slug) => `/tours/${slug}/book`,
  tourDetail: (slug) => `/tours/${slug}`,
  whyUs: "/why-us",
  stories: "/stories",
  storyDetail: (slug) => `/stories/${slug}`,
  contact: "/contact",
  login: "/login",
  signup: "/signup",
  verify: "/verify",
  dashboard: "/dashboard",
  profile: "/profile",
  myInquiries: "/my-inquiries",
  myBookings: "/my-bookings",
  unauthorized: "/unauthorized",
  admin: {
    login: "/admin/login",
    dashboard: "/admin/dashboard",
    users: "/admin/users",
    userNew: "/admin/users/new",
    userDetail: (id) => `/admin/users/${id}`,
    userEdit: (id) => `/admin/users/${id}/edit`,
    clients: "/admin/clients",
    bookings: "/admin/bookings",
    contacts: "/admin/contacts",
    contactDetail: (id) => `/admin/contacts/${id}`,
    listings: "/admin/listings",
    roles: "/admin/roles",
    profile: "/admin/profile",
  },
  operator: {
    dashboard: "/operator/dashboard",
    tours: "/operator/tours",
    tourNew: "/operator/tours/new",
    tourEdit: (id) => `/operator/tours/${id}/edit`,
    bookings: "/operator/bookings",
    profile: "/operator/profile",
  },
};
